-- Seed inicial
--
-- O usuário administrador NÃO é mais criado por aqui (a versão anterior usava a senha "admin").
-- Para criar o primeiro admin com uma senha forte, rode:
--
--   node --env-file=.env.local scripts/create-admin.mjs
--
-- Se o admin antigo (admin@capacitacao.com / senha "admin") já existe no banco,
-- troque a senha dele imediatamente ou exclua-o depois de criar o novo admin.
